import { readdir, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { camelCase } from "./lib/icons.ts"

const siteRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const iconsDirectory = path.join(siteRoot, "src", "assets", "icons")
const componentPath = path.join(siteRoot, "src", "components", "Icon.astro")

async function main(): Promise<void> {
    const files = (await readdir(iconsDirectory)).filter((file) => file.endsWith(".svg")).sort()
    const entries = files.map(
        (file) =>
            `    ${camelCase(file.slice(0, -4))}: (await import("../assets/icons/${file}?raw")).default,`,
    )

    const template = `---
import type { HTMLAttributes } from "astro/types";

interface Props extends HTMLAttributes<"span"> {
    name: string;
}

// This file is generated by scripts/build-icons.ts — do not edit directly.
const icons: Record<string, string> = {
${entries.join("\n")}
};

const { name, class: className, ...rest } = Astro.props;
const source = icons[name] ?? "";
---

<span class:list={["pixel-icon", className]} set:html={source} {...rest} />

<style>
    .pixel-icon {
        align-items: center;
        display: inline-flex;
        flex: 0 0 auto;
        justify-content: center;
        line-height: 0;

        :global(svg) {
            height: 1em;
            width: 1em;
        }
    }
</style>
`

    await writeFile(componentPath, template)
    console.log(`Wrote ${entries.length} icons to ${componentPath}`)
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
    main().catch((error: unknown) => {
        console.error(error)
        process.exitCode = 1
    })
}
