/* oxlint-disable no-await-in-loop */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

import {
    cssDeclarationLines,
    CURATED_DARK,
    CURATED_LIGHT,
    slug,
    translateTheme,
    type ThemeMode,
    type ThemeVariables,
} from "./lib/themes.ts"

const siteRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const themesDirectory = path.join(siteRoot, "src", "data", "themes")
const stylesDirectory = path.join(siteRoot, "src", "styles")

interface Theme {
    id: string
    name: string
    mode: string
    accent: string
    bg: string
    fg: string
    variables: ThemeVariables
}

function toCss(theme: Theme): string {
    return `:root[data-datalith-theme="${theme.id}"] {\n\tcolor-scheme: ${theme.mode};\n${cssDeclarationLines(
        theme.variables,
    )}\n}\n`
}

async function main(): Promise<void> {
    const files = (await readdir(themesDirectory)).filter((file) => file.endsWith(".json"))
    const themes: Theme[] = []
    for (const file of files) {
        const data = JSON.parse(await readFile(path.join(themesDirectory, file), "utf8")) as {
            themes?: Array<{ name: string }>
        }
        for (const entry of data.themes ?? []) {
            const mode: ThemeMode | null = CURATED_DARK.includes(entry.name)
                ? "dark"
                : CURATED_LIGHT.includes(entry.name)
                  ? "light"
                  : null
            if (!mode) continue
            const id = slug(entry.name)
            const variables = translateTheme(entry, mode)
            themes.push({
                id,
                name: entry.name,
                mode,
                accent: variables["--dl-accent"],
                bg: variables["--dl-bg"],
                fg: variables["--dl-fg"],
                variables,
            })
        }
    }

    themes.sort((a, b) => {
        if (a.mode !== b.mode) return a.mode === "light" ? -1 : 1
        return a.name.localeCompare(b.name)
    })

    const defaultTheme = themes.find((theme) => theme.id === "datalith-light")
    if (!defaultTheme) throw new Error("Datalith Light theme is missing from the curated set")
    const css = [
        "/* This file is generated by scripts/build-themes.ts — do not edit directly. */",
        `:root {\n\tcolor-scheme: light;\n${cssDeclarationLines(defaultTheme.variables)}\n}\n`,
        ...themes.map((theme) => toCss(theme)),
    ].join("\n")

    await mkdir(stylesDirectory, { recursive: true })
    await writeFile(path.join(stylesDirectory, "themes.css"), css)
    await writeFile(
        path.join(siteRoot, "src", "data", "themes.json"),
        `${JSON.stringify(
            themes.map(({ variables, ...theme }) => theme),
            null,
            2,
        )}\n`,
    )
    console.log(`Wrote ${themes.length} themes to src/styles/themes.css and src/data/themes.json`)
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
    main().catch((error: unknown) => {
        console.error(error)
        process.exitCode = 1
    })
}
