import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const siteRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const iconsDirectory = path.join(siteRoot, 'src', 'assets', 'icons');
const componentPath = path.join(siteRoot, 'src', 'components', 'Icon.astro');

function camelCase(name) {
	return name
		.split('-')
		.map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
		.join('');
}

const files = (await readdir(iconsDirectory)).filter((file) => file.endsWith('.svg')).sort();
const entries = files.map((file) => `    ${camelCase(file.slice(0, -4))}: (await import("../assets/icons/${file}?raw")).default,`);

const template = `---
import type { HTMLAttributes } from "astro/types";

interface Props extends HTMLAttributes<"span"> {
    name: string;
}

// This file is generated by scripts/build-icons.mjs — do not edit directly.
const icons: Record<string, string> = {
${entries.join('\n')}
};

const { name, class: className, ...rest } = Astro.props;
const source = icons[name] ?? "";
---

<span class:list={["pixel-icon", className]} set:html={source} {...rest} />

<style>
    .pixel-icon {
        align-items: center;
        display: inline-flex;
        flex: 0 0 auto;
        justify-content: center;
        line-height: 0;

        :global(svg) {
            height: 1em;
            width: 1em;
        }
    }
</style>
`;

await writeFile(componentPath, template);
console.log(`Wrote ${entries.length} icons to ${componentPath}`);
